# Generated by Django 4.0.3 on 2022-03-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi_app', '0004_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
